// Product Action Types
export const ProductActionTypes = {
  FETCH_FAILURE: "FETCH_FAILURE",
  FETCH_ALL_PRODUCTS: "FETCH_ALL_PRODUCTS",
  FETCH_CATEGORIES : 'FETCH_CATEGORIES',
};

// Cart Action Types
export const CartActionTypes = {
  FETCH_CART_ITEMS:'FETCH_CART_ITEMS',
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREASE_PROD_QUANTITY: "INCREASE_PROD_QUANTITY",
  DECREASE_PROD_QUANTITY: "DECREASE_PROD_QUANTITY",
};

export const OrderActionTypes = {
  CREATE_ORDER: "CREATE_ORDER",
  CANCEL_ORDER: "CANCEL_ORDER",
};

// Cart Action Types
export const UserActionTypes = {

  USER_FETCH_LOADING: "USER_FETCH_LOADING",
  USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
  USER_FETCH_FAILURE: "USER_FETCH_FAILURE",
};
